### ISSUE TITLE
New fluentd plugin to output to flume

### ISSUE THREAD

**Issue by wd** [fluent/fluent-plugin-flume#6]
I've made some research, and write a plugin(some code from out_netcat) to output message to flume, the codes are here https://github.com/wd/fluent-plugin-flume-thrift.

In recent flume releases, they changed there thrift protocol to https://github.com/wd/fluent-plugin-flume-thrift/blob/master/thrift/flume.thrift, I've tried to fork this repo to fix it to fit flume `org.apache.flume.source.thriftLegacy.ThriftLegacySource` but faild, there still some weird problem.

Maybe the new plugin will help someone out.

**Comment by wd** [comment]
And welcome to fork and make it better, I'm newbie to ruby.

**Comment by repeatedly** [comment]
Ah, good.

> I've tried to fork this repo to fix it to fit flume org.apache.flume.source.thriftLegacy.ThriftLegacySource but faild, there still some weird problem.

Yeah. We want to resolve this problem but we need Flume expert...

**Comment by repeatedly** [comment]
v0.1.2 also includes update output format.

**Comment by repeatedly** [comment]
Thanks contributors!
